package com.scarfilun.penya.model;

import com.scarfilun.equipo.model.Equipo;

// Generated 25-feb-2012 15:52:22 by Hibernate Tools 3.4.0.CR1

/**
 * Penya generated by hbm2java
 */
@SuppressWarnings("serial")
public class Penya implements java.io.Serializable {

	private PenyaId id;
	private Equipo equipo;
	private String nombre;
	private String direccion;
	private String lugarIdentificador;
	private String fechaFundacion;
	private String personaContacto;
	private String telefono;
	private String fax;
	private String email;
	private String web;
	private String numMiembros;
	private String numSocios;

	public Penya() {
	}

	public Penya(PenyaId id, Equipo equipo, String nombre,
			String lugarIdentificador) {
		this.id = id;
		this.equipo = equipo;
		this.nombre = nombre;
		this.lugarIdentificador = lugarIdentificador;
	}

	public Penya(PenyaId id, Equipo equipo, String nombre, String direccion,
			String lugarIdentificador, String fechaFundacion,
			String personaContacto, String telefono, String fax, String email,
			String web, String numMiembros, String numSocios) {
		this.id = id;
		this.equipo = equipo;
		this.nombre = nombre;
		this.direccion = direccion;
		this.lugarIdentificador = lugarIdentificador;
		this.fechaFundacion = fechaFundacion;
		this.personaContacto = personaContacto;
		this.telefono = telefono;
		this.fax = fax;
		this.email = email;
		this.web = web;
		this.numMiembros = numMiembros;
		this.numSocios = numSocios;
	}

	public PenyaId getId() {
		return this.id;
	}

	public void setId(PenyaId id) {
		this.id = id;
	}

	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getLugarIdentificador() {
		return this.lugarIdentificador;
	}

	public void setLugarIdentificador(String lugarIdentificador) {
		this.lugarIdentificador = lugarIdentificador;
	}

	public String getFechaFundacion() {
		return this.fechaFundacion;
	}

	public void setFechaFundacion(String fechaFundacion) {
		this.fechaFundacion = fechaFundacion;
	}

	public String getPersonaContacto() {
		return this.personaContacto;
	}

	public void setPersonaContacto(String personaContacto) {
		this.personaContacto = personaContacto;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWeb() {
		return this.web;
	}

	public void setWeb(String web) {
		this.web = web;
	}

	public String getNumMiembros() {
		return this.numMiembros;
	}

	public void setNumMiembros(String numMiembros) {
		this.numMiembros = numMiembros;
	}

	public String getNumSocios() {
		return this.numSocios;
	}

	public void setNumSocios(String numSocios) {
		this.numSocios = numSocios;
	}

}
